/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for a JWT pair. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a refresh token for a new access token. */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the caller's refresh token. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users in the caller's tenant. */
        get: operations["listUsers"];
        put?: never;
        /** Create a user in the caller's tenant. Admin only. */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID identifier for the resource.
                 * @example 01HZ7S9GYP7V2E8GNQ0F5RHXK1
                 */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Fetch a user by id. */
        get: operations["getUser"];
        put?: never;
        post?: never;
        /** Soft-delete a user. */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        /** Update fields on a user. */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List items in the caller's tenant. */
        get: operations["listItems"];
        put?: never;
        /** Create an item. */
        post: operations["createItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID identifier for the resource.
                 * @example 01HZ7S9GYP7V2E8GNQ0F5RHXK1
                 */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        /** Fetch an item by id. */
        get: operations["getItem"];
        put?: never;
        post?: never;
        /** Soft-delete an item. */
        delete: operations["deleteItem"];
        options?: never;
        head?: never;
        /** Update fields on an item. */
        patch: operations["updateItem"];
        trace?: never;
    };
    "/api/tenants/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the tenant the caller's JWT belongs to. */
        get: operations["getCurrentTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all tenants. Super-admin only. */
        get: operations["listTenants"];
        put?: never;
        /** Create a new tenant. Super-admin only. */
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit log entries scoped to the caller's tenant. */
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 problem detail. */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type: string;
            /** @description Short, human-readable summary of the problem type. */
            title: string;
            /** @description HTTP status code. */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /** @description URI reference identifying this specific occurrence. */
            instance?: string;
        };
        ValidationProblem: components["schemas"]["Problem"] & {
            /** @description Per-field validation errors. */
            errors?: {
                /** @description JSON pointer or field name. */
                field: string;
                /** @description Machine-readable code (e.g. `required`, `format`, `min_length`). */
                code: string;
                /** @description Human-readable message. */
                message: string;
            }[];
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
            /** @description Access token lifetime in seconds. */
            access_expires_in: number;
            /** @description Refresh token lifetime in seconds. */
            refresh_expires_in: number;
        };
        AccessToken: {
            access_token: string;
            access_expires_in: number;
        };
        /**
         * @description Role within a tenant. `super_admin` is cross-tenant and granted
         *     only via the `/api/tenants` endpoints.
         * @enum {string}
         */
        UserRole: "super_admin" | "admin" | "member";
        User: {
            /** Format: ulid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            role: components["schemas"]["UserRole"];
            /** Format: ulid */
            tenant_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateUserRequest: {
            /** Format: email */
            email: string;
            name: string;
            role: components["schemas"]["UserRole"];
            /** Format: password */
            password: string;
        };
        /** @description All fields optional; fields omitted are left unchanged. */
        UpdateUserRequest: {
            name?: string;
            role?: components["schemas"]["UserRole"];
        };
        UserPage: components["schemas"]["PageMeta"] & {
            data: components["schemas"]["User"][];
        };
        Item: {
            /** Format: ulid */
            id: string;
            name: string;
            description?: string;
            /** Format: ulid */
            tenant_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateItemRequest: {
            name: string;
            description?: string;
        };
        /** @description All fields optional. */
        UpdateItemRequest: {
            name?: string;
            description?: string;
        };
        ItemPage: components["schemas"]["PageMeta"] & {
            data: components["schemas"]["Item"][];
        };
        Tenant: {
            /** Format: ulid */
            id: string;
            name: string;
            /** @description URL-safe short identifier, unique globally. */
            slug: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateTenantRequest: {
            name: string;
            slug: string;
        };
        TenantPage: components["schemas"]["PageMeta"] & {
            data: components["schemas"]["Tenant"][];
        };
        AuditLog: {
            /** Format: ulid */
            id: string;
            /**
             * Format: ulid
             * @description User who performed the action.
             */
            actor_id: string;
            /**
             * Format: ulid
             * @description Tenant the action happened within.
             */
            tenant_id: string;
            /** @description Dotted verb, e.g. `user.create`, `item.delete`. */
            action: string;
            /** @description Entity kind the action targets (e.g. `user`, `item`, `tenant`). */
            target_type: string;
            /** Format: ulid */
            target_id: string;
            /** @description Free-form JSON payload; shape depends on `action`. */
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        AuditLogPage: components["schemas"]["PageMeta"] & {
            data: components["schemas"]["AuditLog"][];
        };
        PageMeta: {
            page: number;
            limit: number;
            /** @description Total number of records matching the query. */
            total: number;
        };
    };
    responses: {
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://whitelabel-admin.example.com/errors/unauthorized",
                 *       "title": "Unauthorized",
                 *       "status": 401,
                 *       "detail": "Missing or expired access token.",
                 *       "instance": "/api/users"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authenticated but lacks permission for this operation. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://whitelabel-admin.example.com/errors/forbidden",
                 *       "title": "Forbidden",
                 *       "status": 403,
                 *       "detail": "Admin role required.",
                 *       "instance": "/api/users"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The requested resource does not exist (or isn't visible to the caller's tenant). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://whitelabel-admin.example.com/errors/not-found",
                 *       "title": "Not Found",
                 *       "status": 404,
                 *       "detail": "User not found.",
                 *       "instance": "/api/users/01HZ7S9GYP7V2E8GNQ0F5RHXK1"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request conflicts with existing state (duplicate, version mismatch, etc.). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://whitelabel-admin.example.com/errors/conflict",
                 *       "title": "Conflict",
                 *       "status": 409,
                 *       "detail": "A user with this email already exists.",
                 *       "instance": "/api/users"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request body or parameters failed schema validation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://whitelabel-admin.example.com/errors/validation",
                 *       "title": "Validation Failed",
                 *       "status": 422,
                 *       "detail": "One or more fields are invalid.",
                 *       "instance": "/api/users",
                 *       "errors": [
                 *         {
                 *           "field": "email",
                 *           "code": "format",
                 *           "message": "Must be a valid email."
                 *         },
                 *         {
                 *           "field": "password",
                 *           "code": "min_length",
                 *           "message": "Minimum length is 8 characters."
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
        /** @description Unexpected error. Correlate with logs via `instance`. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://whitelabel-admin.example.com/errors/internal",
                 *       "title": "Internal Server Error",
                 *       "status": 500,
                 *       "detail": "An unexpected error occurred.",
                 *       "instance": "/api/users"
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /**
         * @description ULID identifier for the resource.
         * @example 01HZ7S9GYP7V2E8GNQ0F5RHXK1
         */
        IdParam: string;
        /**
         * @description 1-indexed page number.
         * @example 1
         */
        PageParam: number;
        /**
         * @description Page size. Hard max 100.
         * @example 20
         */
        LimitParam: number;
        /**
         * @description Sort expression as `<field>:<asc|desc>`. Default `created_at:desc`.
         * @example created_at:desc
         */
        SortParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "alice@example.com",
                 *       "password": "hunter2!"
                 *     }
                 */
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. Returns access + refresh tokens. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                     *       "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                     *       "access_expires_in": 900,
                     *       "refresh_expires_in": 2592000
                     *     }
                     */
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                 *     }
                 */
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description New access token issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                     *       "access_expires_in": 900
                     *     }
                     */
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                 *     }
                 */
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Refresh token revoked. No content returned. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /**
                 * @description 1-indexed page number.
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Page size. Hard max 100.
                 * @example 20
                 */
                limit?: components["parameters"]["LimitParam"];
                /**
                 * @description Sort expression as `<field>:<asc|desc>`. Default `created_at:desc`.
                 * @example created_at:desc
                 */
                sort?: components["parameters"]["SortParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "id": "01HZ7S9GYP7V2E8GNQ0F5RHXK1",
                     *           "email": "alice@example.com",
                     *           "name": "Alice Chen",
                     *           "role": "admin",
                     *           "tenant_id": "01HZ0RZ3T1HFGJ2EKD6M1Q3V2B",
                     *           "created_at": "2026-04-10T09:15:00Z",
                     *           "updated_at": "2026-04-12T11:30:00Z"
                     *         }
                     *       ],
                     *       "page": 1,
                     *       "limit": 20,
                     *       "total": 1
                     *     }
                     */
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "bob@example.com",
                 *       "name": "Bob Lee",
                 *       "role": "member",
                 *       "password": "initial-pw!"
                 *     }
                 */
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "01HZ7SBCYN2J6R4QHCT5N8M0WX",
                     *       "email": "bob@example.com",
                     *       "name": "Bob Lee",
                     *       "role": "member",
                     *       "tenant_id": "01HZ0RZ3T1HFGJ2EKD6M1Q3V2B",
                     *       "created_at": "2026-04-16T17:20:00Z",
                     *       "updated_at": "2026-04-16T17:20:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID identifier for the resource.
                 * @example 01HZ7S9GYP7V2E8GNQ0F5RHXK1
                 */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "01HZ7S9GYP7V2E8GNQ0F5RHXK1",
                     *       "email": "alice@example.com",
                     *       "name": "Alice Chen",
                     *       "role": "admin",
                     *       "tenant_id": "01HZ0RZ3T1HFGJ2EKD6M1Q3V2B",
                     *       "created_at": "2026-04-10T09:15:00Z",
                     *       "updated_at": "2026-04-12T11:30:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID identifier for the resource.
                 * @example 01HZ7S9GYP7V2E8GNQ0F5RHXK1
                 */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted. No content returned. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID identifier for the resource.
                 * @example 01HZ7S9GYP7V2E8GNQ0F5RHXK1
                 */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Alice Chen-Wu",
                 *       "role": "admin"
                 *     }
                 */
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "01HZ7S9GYP7V2E8GNQ0F5RHXK1",
                     *       "email": "alice@example.com",
                     *       "name": "Alice Chen-Wu",
                     *       "role": "admin",
                     *       "tenant_id": "01HZ0RZ3T1HFGJ2EKD6M1Q3V2B",
                     *       "created_at": "2026-04-10T09:15:00Z",
                     *       "updated_at": "2026-04-16T17:25:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    listItems: {
        parameters: {
            query?: {
                /**
                 * @description 1-indexed page number.
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Page size. Hard max 100.
                 * @example 20
                 */
                limit?: components["parameters"]["LimitParam"];
                /**
                 * @description Sort expression as `<field>:<asc|desc>`. Default `created_at:desc`.
                 * @example created_at:desc
                 */
                sort?: components["parameters"]["SortParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "id": "01HZ80BDKX3F2N7QKVD2ZEFPCW",
                     *           "name": "Blue Widget",
                     *           "description": "A widget, coloured blue.",
                     *           "tenant_id": "01HZ0RZ3T1HFGJ2EKD6M1Q3V2B",
                     *           "created_at": "2026-04-15T08:00:00Z",
                     *           "updated_at": "2026-04-15T08:00:00Z"
                     *         }
                     *       ],
                     *       "page": 1,
                     *       "limit": 20,
                     *       "total": 1
                     *     }
                     */
                    "application/json": components["schemas"]["ItemPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Red Widget",
                 *       "description": "A widget, coloured red."
                 *     }
                 */
                "application/json": components["schemas"]["CreateItemRequest"];
            };
        };
        responses: {
            /** @description Item created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "01HZ80C7V3YP5K8NC1W2HTFCAR",
                     *       "name": "Red Widget",
                     *       "description": "A widget, coloured red.",
                     *       "tenant_id": "01HZ0RZ3T1HFGJ2EKD6M1Q3V2B",
                     *       "created_at": "2026-04-16T17:30:00Z",
                     *       "updated_at": "2026-04-16T17:30:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Item"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID identifier for the resource.
                 * @example 01HZ7S9GYP7V2E8GNQ0F5RHXK1
                 */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "01HZ80BDKX3F2N7QKVD2ZEFPCW",
                     *       "name": "Blue Widget",
                     *       "description": "A widget, coloured blue.",
                     *       "tenant_id": "01HZ0RZ3T1HFGJ2EKD6M1Q3V2B",
                     *       "created_at": "2026-04-15T08:00:00Z",
                     *       "updated_at": "2026-04-15T08:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Item"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID identifier for the resource.
                 * @example 01HZ7S9GYP7V2E8GNQ0F5RHXK1
                 */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item deleted. No content returned. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ULID identifier for the resource.
                 * @example 01HZ7S9GYP7V2E8GNQ0F5RHXK1
                 */
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "description": "A widget, very blue."
                 *     }
                 */
                "application/json": components["schemas"]["UpdateItemRequest"];
            };
        };
        responses: {
            /** @description Updated item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "01HZ80BDKX3F2N7QKVD2ZEFPCW",
                     *       "name": "Blue Widget",
                     *       "description": "A widget, very blue.",
                     *       "tenant_id": "01HZ0RZ3T1HFGJ2EKD6M1Q3V2B",
                     *       "created_at": "2026-04-15T08:00:00Z",
                     *       "updated_at": "2026-04-16T17:32:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Item"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    getCurrentTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's tenant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "01HZ0RZ3T1HFGJ2EKD6M1Q3V2B",
                     *       "name": "Acme Corp",
                     *       "slug": "acme",
                     *       "created_at": "2026-01-02T00:00:00Z",
                     *       "updated_at": "2026-03-20T10:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTenants: {
        parameters: {
            query?: {
                /**
                 * @description 1-indexed page number.
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Page size. Hard max 100.
                 * @example 20
                 */
                limit?: components["parameters"]["LimitParam"];
                /**
                 * @description Sort expression as `<field>:<asc|desc>`. Default `created_at:desc`.
                 * @example created_at:desc
                 */
                sort?: components["parameters"]["SortParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of tenants. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "id": "01HZ0RZ3T1HFGJ2EKD6M1Q3V2B",
                     *           "name": "Acme Corp",
                     *           "slug": "acme",
                     *           "created_at": "2026-01-02T00:00:00Z",
                     *           "updated_at": "2026-03-20T10:00:00Z"
                     *         }
                     *       ],
                     *       "page": 1,
                     *       "limit": 20,
                     *       "total": 1
                     *     }
                     */
                    "application/json": components["schemas"]["TenantPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Beta Co",
                 *       "slug": "beta"
                 *     }
                 */
                "application/json": components["schemas"]["CreateTenantRequest"];
            };
        };
        responses: {
            /** @description Tenant created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "01HZ80DX5J2HM9QN7VTGCB3PER",
                     *       "name": "Beta Co",
                     *       "slug": "beta",
                     *       "created_at": "2026-04-16T17:35:00Z",
                     *       "updated_at": "2026-04-16T17:35:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                /**
                 * @description 1-indexed page number.
                 * @example 1
                 */
                page?: components["parameters"]["PageParam"];
                /**
                 * @description Page size. Hard max 100.
                 * @example 20
                 */
                limit?: components["parameters"]["LimitParam"];
                /** @description Filter to entries produced by this actor. */
                actor_id?: string;
                /** @description Filter to entries with this action verb (e.g. `user.create`). */
                action?: string;
                /** @description Filter to entries whose target is of this type (e.g. `user`, `item`). */
                target_type?: string;
                /** @description Filter to entries targeting this specific record. */
                target_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of audit log entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "data": [
                     *         {
                     *           "id": "01HZ80F2G6K3N9R7VTYF5HPE8X",
                     *           "actor_id": "01HZ7S9GYP7V2E8GNQ0F5RHXK1",
                     *           "tenant_id": "01HZ0RZ3T1HFGJ2EKD6M1Q3V2B",
                     *           "action": "user.update",
                     *           "target_type": "user",
                     *           "target_id": "01HZ7SBCYN2J6R4QHCT5N8M0WX",
                     *           "metadata": {
                     *             "changed_fields": [
                     *               "name",
                     *               "role"
                     *             ]
                     *           },
                     *           "created_at": "2026-04-16T17:26:00Z"
                     *         }
                     *       ],
                     *       "page": 1,
                     *       "limit": 20,
                     *       "total": 1
                     *     }
                     */
                    "application/json": components["schemas"]["AuditLogPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
